language: node_js
node_js:
- stable
deploy:
  provider: npm
  email: 86287344@qq.com
  skip_cleanup: true
  api_key:
    secure: YKSCFCOMWcIHmSFgSkJ5QDAY2uiIj/eHGoeH4GjyZZ9u4UWn0+c1GMORcEOTgWjx672m42AAGr5uWRjlzi/AqPZBlhK8chnvyc5mdmFVj2XkqiYsoaEL5WeQOMiYpw370efo1zbQEYSy/93gcZNDtonASgrwTXWxC7seJF013JkGVhqEyijIFKXNABNJYWXQ3aSOzP4HVr4SpeyEzBtoM7axCUlVkctO6SR335DzDrsi1K0lQ0iG8HFgJe37QcLjuRnDPIeqzE+cvhIIsGe33CX/DPpKnJx5yizhoOMF/Lsi7jQZgukEti/18SCW4iYGLp8boF2Sl3LcKzzY6fUc0wwKG/Z6J+8hDM1w+yd4WNpwEKZMg9v/X+YoCtbrPirst40cec3fwDpMlFO2rKNQvlu+7XdQzXyDqUagK068YWBQQ1zqUnyeJEnBVYzhUhasDqVP6l584zF/vXJJp4I2oATLqsHpLR3ejDJaOaml/fBYSFfSew/Nb3L4kYJi+g4P/uw+IBDxghoYvX7Nd+zApcjKsDRCqbhIBlHSnIujh0aF+u4+ObftEQAEB7cXI8IWM0ecDj7UrpTg4Oo9OsoY2dhCiXzAgqoxDpqP1J8siD39dQ/Dp9m8W4q5s7jlR5S658krbvRM/gdFvbWCXkbnGbyM2kZzHySC36EDy9ZEfhg=
